# Generated by Django 4.1 on 2023-01-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_admin_app1foodcategory_app1fooditem_app1tablebooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='app_1.usersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('usersmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_1.usersmodel')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_tems', to='app_1.cart')),
            ],
            bases=('app_1.usersmodel',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('u_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('order_status', models.CharField(default='Confirm', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('order_d_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100)),
                ('fi_id', models.IntegerField()),
                ('fi_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='App1FoodCategory',
        ),
        migrations.DeleteModel(
            name='App1Fooditem',
        ),
        migrations.DeleteModel(
            name='App1TableBooking',
        ),
        migrations.DeleteModel(
            name='App1Usersmodel',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.DeleteModel(
            name='HallBooking',
        ),
        migrations.DeleteModel(
            name='PartyOrder',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(default='', upload_to='pic1/'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='fooditem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.fooditem'),
        ),
    ]
