# Generated by Django 4.1 on 2022-12-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_food_category_fc_id_alter_usersmodel_u_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
