# Generated by Django 4.1 on 2022-12-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_admin_app1foodcategory_app1fooditem_app1tablebooking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallBooking',
        ),
        migrations.DeleteModel(
            name='PartyOrder',
        ),
    ]
