# Generated by Django 4.1 on 2022-12-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_delete_hallbooking_delete_partyorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App1FoodCategory',
        ),
    ]
