# Generated by Django 4.1 on 2023-01-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_delete_app1foodcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
    ]
