# Generated by Django 4.1 on 2023-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_alter_admin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='admin',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='admin',
            table=None,
        ),
    ]
