# Generated by Django 4.1 on 2023-01-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_admin_admin_id_alter_admin_admin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App1FoodCategory',
            fields=[
                ('fc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fc_name', models.CharField(max_length=100, unique=True)),
                ('fc_description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'app_1_food_category',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='DjangoSite',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
    ]
