# Generated by Django 4.1 on 2023-01-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_app1foodcategory_delete_djangosession_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('order_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('total_amount', models.IntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usersmodel')),
            ],
        ),
    ]
