# Generated by Django 4.1 on 2023-01-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_alter_admin_table_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
