# Generated by Django 4.1 on 2023-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_alter_order_details_fi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
