# Generated by Django 4.1 on 2023-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='fi_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
