# Generated by Django 4.1 on 2023-01-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0019_order_details_fi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_items',
        ),
    ]
