# Generated by Django 4.1 on 2023-01-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0020_remove_order_total_amount_remove_order_total_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
