# Generated by Django 4.1 on 2023-01-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0021_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_id',
            field=models.CharField(max_length=100),
        ),
    ]
