# Generated by Django 4.1 on 2023-01-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0022_alter_order_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(upload_to='food_image/'),
        ),
    ]
