# Generated by Django 4.1 on 2023-01-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0027_alter_fooditem_food_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App1FoodCategory',
        ),
        migrations.DeleteModel(
            name='App1Fooditem',
        ),
        migrations.DeleteModel(
            name='App1TableBooking',
        ),
        migrations.DeleteModel(
            name='App1Usersmodel',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
