# Generated by Django 4.1 on 2023-01-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_usersmodel_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_image',
            field=models.FileField(default='', upload_to='pic/'),
        ),
    ]
