# Generated by Django 4.1 on 2023-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_fooditem_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_image',
            field=models.ImageField(default='', upload_to='FOOD_IMAGE/'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='user_image',
            field=models.ImageField(default='', upload_to='User_Image/'),
        ),
    ]
