# Generated by Django 4.1 on 2023-01-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_alter_order_details_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='order_id',
        ),
    ]
