# Generated by Django 4.1 on 2023-01-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_remove_order_details_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
