# Generated by Django 4.1 on 2023-01-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_table_booking_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_id',
            field=models.ImageField(upload_to=''),
        ),
    ]
