# Generated by Django 4.1 on 2023-01-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0013_alter_order_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='t_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
