# Generated by Django 4.1 on 2023-02-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_order_details_t_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='u_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
