# Generated by Django 4.1 on 2023-02-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_event_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='u_id',
        ),
        migrations.AddField(
            model_name='event',
            name='u_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
