# Generated by Django 4.1 on 2023-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_remove_event_u_id_event_u_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='u_id',
        ),
        migrations.AddField(
            model_name='order',
            name='u_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
