# Generated by Django 4.1 on 2023-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_remove_order_u_id_order_u_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='u_name',
        ),
        migrations.AddField(
            model_name='order',
            name='u_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
