# Generated by Django 4.1 on 2023-02-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_remove_order_u_name_order_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='u_name',
        ),
        migrations.AddField(
            model_name='event',
            name='u_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
