# Generated by Django 4.1 on 2023-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0019_remove_event_u_name_event_u_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pragneysh',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_what', models.CharField(max_length=500)),
            ],
        ),
    ]
