# Generated by Django 4.1 on 2023-02-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0020_pragneysh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pragneysh',
        ),
    ]
