# Generated by Django 4.1 on 2023-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0023_delete_pragneysh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall_Booking',
            fields=[
                ('hb_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
