# Generated by Django 4.1 on 2023-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0024_hall_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_booking',
            name='end_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall_booking',
            name='event_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall_booking',
            name='start_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
