# Generated by Django 4.1 on 2023-02-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0025_hall_booking_end_time_hall_booking_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_menu_category',
            fields=[
                ('emc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emc_name', models.CharField(max_length=100, unique=True)),
                ('emc_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event_menu_item',
            fields=[
                ('emi_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('emi_name', models.CharField(max_length=500)),
                ('emi_price', models.IntegerField()),
                ('emi_image', models.ImageField(default='', upload_to='Event_menu_item/')),
                ('emi_category', models.CharField(max_length=100)),
            ],
        ),
    ]
