# Generated by Django 4.1 on 2023-02-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0027_alter_event_menu_category_emc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_menu_item',
            name='emi_image',
        ),
    ]
