# Generated by Django 4.1 on 2023-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0028_remove_event_menu_item_emi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_menu_item',
            name='emi_lavel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
