# Generated by Django 4.1 on 2023-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0029_event_menu_item_emi_lavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_menu',
            fields=[
                ('em_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('u_id', models.IntegerField()),
                ('emi_id', models.IntegerField()),
                ('emi_name', models.CharField(max_length=500)),
            ],
        ),
    ]
