# Generated by Django 4.1 on 2023-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0031_alter_event_menu_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_menu',
            name='emi_peice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
