# Generated by Django 4.1 on 2023-02-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0033_event_menu_emi_category_alter_event_menu_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_menu',
            name='emi_category',
            field=models.CharField(max_length=500),
        ),
    ]
