# Generated by Django 4.1 on 2023-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0034_alter_event_menu_emi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_booking',
            name='u_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
