# Generated by Django 4.1 on 2023-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0035_table_booking_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall_booking',
            name='u_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
