# Generated by Django 4.1 on 2023-02-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0036_hall_booking_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='fooditem',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='usersmodel_ptr',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
