# Generated by Django 4.1 on 2023-02-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0037_remove_cartitems_cart_remove_cartitems_fooditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='a_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='p_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
