# Generated by Django 4.1 on 2023-02-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0038_event_a_price_event_p_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='a_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='p_price',
            field=models.IntegerField(null=True),
        ),
    ]
