# Generated by Django 4.1 on 2023-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0039_alter_event_a_price_alter_event_p_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='t_p',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
