# Generated by Django 4.1 on 2023-02-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0040_order_items_order_t_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='t_p',
            field=models.IntegerField(null=True),
        ),
    ]
