# Generated by Django 4.1 on 2022-12-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('fi_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('categories', models.CharField(max_length=100)),
                ('food_price', models.IntegerField(max_length=100)),
                ('food_description', models.CharField(max_length=1000)),
                ('food_image', models.ImageField(upload_to='pic/')),
            ],
        ),
    ]
