# Generated by Django 4.1 on 2022-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_price',
            field=models.IntegerField(),
        ),
    ]
