# Generated by Django 4.1 on 2022-12-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_fooditem_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_name', models.CharField(max_length=100)),
                ('tb_contact', models.CharField(max_length=10)),
                ('tb_email', models.EmailField(max_length=254)),
                ('tb_no_guest', models.IntegerField(max_length=2)),
                ('tb_date', models.DateField()),
                ('tb_time', models.IntegerField()),
                ('table_type', models.TextField(max_length=25)),
                ('tb_choose', models.CharField(max_length=10)),
            ],
        ),
    ]
