# Generated by Django 4.1 on 2022-12-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_table_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(db_column='Admin_ID', primary_key=True, serialize=False)),
                ('admin_name', models.CharField(db_column='Admin_Name', max_length=50)),
                ('admin_password', models.CharField(db_column='Admin_Password', max_length=8)),
                ('email_id', models.CharField(db_column='Email_ID', max_length=50)),
                ('contact_number', models.BigIntegerField(db_column='Contact_Number')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1FoodCategory',
            fields=[
                ('fc_id', models.AutoField(primary_key=True, serialize=False)),
                ('fc_name', models.CharField(max_length=100, unique=True)),
                ('fc_description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'app_1_food_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Fooditem',
            fields=[
                ('fi_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('categories', models.CharField(max_length=100)),
                ('food_price', models.IntegerField()),
                ('food_description', models.CharField(max_length=1000)),
                ('food_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_1_fooditem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1TableBooking',
            fields=[
                ('tb_name', models.CharField(max_length=100)),
                ('tb_contact', models.CharField(max_length=10)),
                ('tb_email', models.CharField(max_length=254)),
                ('tb_no_guest', models.IntegerField()),
                ('tb_date', models.DateField()),
                ('tb_time', models.TextField()),
                ('table_type', models.TextField()),
                ('tb_choose', models.CharField(max_length=10)),
                ('tb_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_1_table_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App1Usersmodel',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('u_address', models.CharField(max_length=100)),
                ('u_city', models.CharField(max_length=100)),
                ('u_pin_code', models.IntegerField(blank=True, null=True)),
                ('user_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_1_usersmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('combo_name', models.CharField(max_length=100)),
                ('combo_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'combo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComboDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'combo_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='Customer_Name', max_length=25)),
                ('customer_password', models.CharField(db_column='Customer_Password', max_length=8)),
                ('email_id', models.TextField(db_column='Email_ID')),
                ('contact_number', models.BigIntegerField(db_column='Contact_Number')),
                ('address', models.CharField(db_column='Address', max_length=150)),
                ('city', models.CharField(db_column='City', max_length=20)),
                ('pin_code', models.IntegerField(db_column='Pin_code')),
                ('image', models.CharField(blank=True, db_column='Image', max_length=150, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomizationDetail',
            fields=[
                ('custom_id', models.AutoField(db_column='Custom_Id', primary_key=True, serialize=False)),
                ('custm_des', models.CharField(db_column='Custm_Des', max_length=50)),
            ],
            options={
                'db_table': 'customization detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_what', models.CharField(max_length=500)),
                ('event_date_time', models.DateTimeField()),
                ('delivery_add', models.CharField(max_length=100)),
                ('number_of_person', models.IntegerField()),
                ('alt_contactno', models.BigIntegerField(db_column='alt_contactNO')),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(db_column='Food_id', primary_key=True, serialize=False)),
                ('food_name', models.CharField(db_column='Food_name', max_length=50)),
                ('food_price', models.DecimalField(db_column='Food_price', decimal_places=2, max_digits=10)),
                ('food_image', models.CharField(db_column='Food_Image', max_length=150)),
                ('description', models.CharField(db_column='Description', max_length=150)),
                ('cat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_order_id', models.IntegerField()),
                ('food_id', models.IntegerField(db_column='Food_id')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'food_order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('hall_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_person', models.IntegerField(db_column='No_Person')),
                ('date_time_start_field', models.DateTimeField(db_column='Date/Time(Start)')),
                ('time_end_field', models.TimeField(db_column='Time(End)')),
                ('fun_info', models.CharField(db_column='Fun_Info', max_length=500)),
            ],
            options={
                'db_table': 'hall_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCustomization',
            fields=[
                ('customization_id', models.AutoField(db_column='Customization_Id', primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(db_column='Item_Id')),
                ('customer_id', models.IntegerField(db_column='Customer_Id')),
                ('chaege', models.FloatField()),
            ],
            options={
                'db_table': 'item customization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField(db_column='Package_ID')),
                ('food_id', models.IntegerField()),
            ],
            options={
                'db_table': 'package_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.IntegerField(db_column='Package_ID', primary_key=True, serialize=False)),
                ('package_name', models.CharField(db_column='Package_name', max_length=100)),
                ('package_price', models.DecimalField(db_column='Package_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'packages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartyOrder',
            fields=[
                ('party_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(db_column='Customer_ID')),
                ('event_id', models.IntegerField()),
            ],
            options={
                'db_table': 'party_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartyOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_order_id', models.IntegerField()),
                ('package_id', models.IntegerField(db_column='package_ID')),
            ],
            options={
                'db_table': 'party_order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcat_id', models.AutoField(db_column='Subcat_Id', primary_key=True, serialize=False)),
                ('cat_id', models.IntegerField(db_column='Cat_Id')),
                ('subcat_name', models.CharField(db_column='SubCat_Name', max_length=20)),
            ],
            options={
                'db_table': 'sub_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('booking_id', models.AutoField(db_column='Booking_id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
            ],
            options={
                'db_table': 'table_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('table_number', models.CharField(db_column='Table_Number', max_length=9, primary_key=True, serialize=False)),
                ('table_capacity', models.IntegerField(db_column='Table_Capacity')),
                ('table_price', models.DecimalField(db_column='Table_price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tables',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='table_booking',
            name='id',
        ),
        migrations.AddField(
            model_name='table_booking',
            name='tb_id',
            field=models.IntegerField(auto_created=True, default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='u_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='u_city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='u_pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='user_image',
            field=models.ImageField(default='', upload_to='pic/'),
        ),
        migrations.AlterField(
            model_name='table_booking',
            name='tb_no_guest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_booking',
            name='tb_time',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('food_order', models.OneToOneField(db_column='Food_Order_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_1.food')),
            ],
            options={
                'db_table': 'food_order',
                'managed': False,
            },
        ),
    ]
