# Generated by Django 4.1 on 2022-12-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_remove_table_booking_id_table_booking_tb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='re_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
