# Generated by Django 4.1 on 2022-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_usersmodel_re_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='u_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
