# Generated by Django 4.1 on 2022-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_usersmodel_u_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='u_city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
