# Generated by Django 4.1 on 2022-12-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_usersmodel_u_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_booking',
            name='tb_no_guest',
            field=models.IntegerField(),
        ),
    ]
