# Generated by Django 4.1 on 2022-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_alter_table_booking_tb_no_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='u_pin_code',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
