# Generated by Django 4.1 on 2022-12-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_table_booking_tb_no_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='u_pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
